# Generated by Django 5.2.10 on 2026-01-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_1', models.IntegerField(blank=True, default=0, null=True)),
                ('var_2', models.CharField(blank=True, default=0, max_length=20, null=True)),
            ],
        ),
    ]
